# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kakeibo.swalloworkstudio.com
title: 毎日家計簿	
email: swalloworks@gmail.com
author: Jack
description: > # "家計簿 家計簿アプリ 家計簿無料 家計簿おすすめ 家計簿無料おすすめ 家計簿　おすすめ 小遣い帳 お金管理アプリ かんたん 収支 レシート 支出 簡単 シンプル 便利 フリー マネー お金 管理 節約 kakeibo プロー free money expense spend 记账 账本"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: http://twitter.com/swalloworks
  - title: facebook
    url: https://www.facebook.com/kakeibomainichi/
