# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kakeibo.swalloworkstudio.com
title: 毎日家計簿	
email: swalloworks@gmail.com
author: Your Name
description: > # "家計簿 小遣い帳 かんたん 収支 レシート 支出 簡単 シンプル 便利 フリー マネー お金 管理 節約 kakeibo プロー free money expense spend 记账 账本"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: http://twitter.com/swalloworks
  - title: linkedin
    url: http://jp.linkedin.com/pub/xuan-renliang/40/68/ba4
